version: "3.8"

services:
  migration-backend:
    build: .
    container_name: pokt-migration-backend
    ports:
      - "8086:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - CORS_ORIGIN=https://migration.shannon.nodefleet.net,http://localhost:5173
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - pokt-network
      - traefik-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.migration-backend.rule=Host(`api.migration.shannon.nodefleet.net`)"
      - "traefik.http.routers.migration-backend.entrypoints=websecure"
      - "traefik.http.routers.migration-backend.tls=true"
      - "traefik.http.routers.migration-backend.tls.certresolver=https-resolver"
      - "traefik.http.services.migration-backend.loadbalancer.server.port=3001"
      - "traefik.http.routers.migration-backend-http.rule=Host(`api.migration.shannon.nodefleet.net`)"
      - "traefik.http.routers.migration-backend-http.entrypoints=web"
      - "traefik.http.routers.migration-backend-http.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"
      - "traefik.docker.network=traefik-network"

  # Optional: Add a reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: pokt-migration-nginx
    restart: unless-stopped
    ports:
      - "${NGINX_PORT:-8080}:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - migration-backend
    networks:
      - pokt-network
    profiles:
      - with-nginx

volumes:
  migration_data:
    driver: local
  migration_logs:
    driver: local

networks:
  pokt-network:
    driver: bridge
  traefik-network:
    external: true
    name: traefik-network
